// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/android_channel.proto

package com.google.protos.ipc.invalidation;

public final class AndroidChannel {
  private AndroidChannel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum MajorVersion
      implements com.google.protobuf.Internal.EnumLite {
    INITIAL(0, 0),
    BATCH(1, 1),
    ;
    
    public static final MajorVersion DEFAULT = INITIAL;
    public static final MajorVersion MIN_SUPPORTED = INITIAL;
    public static final MajorVersion MAX_SUPPORTED = BATCH;
    
    public final int getNumber() { return value; }
    
    public static MajorVersion valueOf(int value) {
      switch (value) {
        case 0: return INITIAL;
        case 1: return BATCH;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MajorVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MajorVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MajorVersion>() {
            public MajorVersion findValueByNumber(int number) {
              return MajorVersion.valueOf(number)
    ;        }
          };
    
    private final int index;
    private final int value;
    private MajorVersion(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.MajorVersion)
  }
  
  public static final class EndpointId extends
      com.google.protobuf.GeneratedMessageLite {
    // Use EndpointId.newBuilder() to construct.
    private EndpointId() {
      initFields();
    }
    private EndpointId(boolean noInit) {}
    
    private static final EndpointId defaultInstance;
    public static EndpointId getDefaultInstance() {
      return defaultInstance;
    }
    
    public EndpointId getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .com.google.protos.ipc.invalidation.ProtocolVersion protocol_version = 1;
    public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
    private boolean hasProtocolVersion;
    private com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion protocolVersion_;
    public boolean hasProtocolVersion() { return hasProtocolVersion; }
    public com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion getProtocolVersion() { return protocolVersion_; }
    
    // optional string c2dm_registration_id = 2;
    public static final int C2DM_REGISTRATION_ID_FIELD_NUMBER = 2;
    private boolean hasC2DmRegistrationId;
    private java.lang.String c2DmRegistrationId_ = "";
    public boolean hasC2DmRegistrationId() { return hasC2DmRegistrationId; }
    public java.lang.String getC2DmRegistrationId() { return c2DmRegistrationId_; }
    
    // optional string client_key = 3;
    public static final int CLIENT_KEY_FIELD_NUMBER = 3;
    private boolean hasClientKey;
    private java.lang.String clientKey_ = "";
    public boolean hasClientKey() { return hasClientKey; }
    public java.lang.String getClientKey() { return clientKey_; }
    
    // optional string sender_id = 4;
    public static final int SENDER_ID_FIELD_NUMBER = 4;
    private boolean hasSenderId;
    private java.lang.String senderId_ = "";
    public boolean hasSenderId() { return hasSenderId; }
    public java.lang.String getSenderId() { return senderId_; }
    
    // optional .com.google.protos.ipc.invalidation.Version channel_version = 5;
    public static final int CHANNEL_VERSION_FIELD_NUMBER = 5;
    private boolean hasChannelVersion;
    private com.google.protos.ipc.invalidation.ClientProtocol.Version channelVersion_;
    public boolean hasChannelVersion() { return hasChannelVersion; }
    public com.google.protos.ipc.invalidation.ClientProtocol.Version getChannelVersion() { return channelVersion_; }
    
    // optional string package_name = 6;
    public static final int PACKAGE_NAME_FIELD_NUMBER = 6;
    private boolean hasPackageName;
    private java.lang.String packageName_ = "";
    public boolean hasPackageName() { return hasPackageName; }
    public java.lang.String getPackageName() { return packageName_; }
    
    private void initFields() {
      protocolVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion.getDefaultInstance();
      channelVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProtocolVersion()) {
        output.writeMessage(1, getProtocolVersion());
      }
      if (hasC2DmRegistrationId()) {
        output.writeString(2, getC2DmRegistrationId());
      }
      if (hasClientKey()) {
        output.writeString(3, getClientKey());
      }
      if (hasSenderId()) {
        output.writeString(4, getSenderId());
      }
      if (hasChannelVersion()) {
        output.writeMessage(5, getChannelVersion());
      }
      if (hasPackageName()) {
        output.writeString(6, getPackageName());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProtocolVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProtocolVersion());
      }
      if (hasC2DmRegistrationId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getC2DmRegistrationId());
      }
      if (hasClientKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getClientKey());
      }
      if (hasSenderId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSenderId());
      }
      if (hasChannelVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getChannelVersion());
      }
      if (hasPackageName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getPackageName());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.EndpointId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidChannel.EndpointId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidChannel.EndpointId, Builder> {
      private com.google.protos.ipc.invalidation.AndroidChannel.EndpointId result;
      
      // Construct using com.google.protos.ipc.invalidation.AndroidChannel.EndpointId.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.AndroidChannel.EndpointId();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.AndroidChannel.EndpointId internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.AndroidChannel.EndpointId();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.AndroidChannel.EndpointId getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidChannel.EndpointId.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.AndroidChannel.EndpointId build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.AndroidChannel.EndpointId buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.AndroidChannel.EndpointId buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.AndroidChannel.EndpointId returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidChannel.EndpointId other) {
        if (other == com.google.protos.ipc.invalidation.AndroidChannel.EndpointId.getDefaultInstance()) return this;
        if (other.hasProtocolVersion()) {
          mergeProtocolVersion(other.getProtocolVersion());
        }
        if (other.hasC2DmRegistrationId()) {
          setC2DmRegistrationId(other.getC2DmRegistrationId());
        }
        if (other.hasClientKey()) {
          setClientKey(other.getClientKey());
        }
        if (other.hasSenderId()) {
          setSenderId(other.getSenderId());
        }
        if (other.hasChannelVersion()) {
          mergeChannelVersion(other.getChannelVersion());
        }
        if (other.hasPackageName()) {
          setPackageName(other.getPackageName());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion.Builder subBuilder = com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion.newBuilder();
              if (hasProtocolVersion()) {
                subBuilder.mergeFrom(getProtocolVersion());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProtocolVersion(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setC2DmRegistrationId(input.readString());
              break;
            }
            case 26: {
              setClientKey(input.readString());
              break;
            }
            case 34: {
              setSenderId(input.readString());
              break;
            }
            case 42: {
              com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder subBuilder = com.google.protos.ipc.invalidation.ClientProtocol.Version.newBuilder();
              if (hasChannelVersion()) {
                subBuilder.mergeFrom(getChannelVersion());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChannelVersion(subBuilder.buildPartial());
              break;
            }
            case 50: {
              setPackageName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.ProtocolVersion protocol_version = 1;
      public boolean hasProtocolVersion() {
        return result.hasProtocolVersion();
      }
      public com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion getProtocolVersion() {
        return result.getProtocolVersion();
      }
      public Builder setProtocolVersion(com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasProtocolVersion = true;
        result.protocolVersion_ = value;
        return this;
      }
      public Builder setProtocolVersion(com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion.Builder builderForValue) {
        result.hasProtocolVersion = true;
        result.protocolVersion_ = builderForValue.build();
        return this;
      }
      public Builder mergeProtocolVersion(com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion value) {
        if (result.hasProtocolVersion() &&
            result.protocolVersion_ != com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion.getDefaultInstance()) {
          result.protocolVersion_ =
            com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion.newBuilder(result.protocolVersion_).mergeFrom(value).buildPartial();
        } else {
          result.protocolVersion_ = value;
        }
        result.hasProtocolVersion = true;
        return this;
      }
      public Builder clearProtocolVersion() {
        result.hasProtocolVersion = false;
        result.protocolVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.ProtocolVersion.getDefaultInstance();
        return this;
      }
      
      // optional string c2dm_registration_id = 2;
      public boolean hasC2DmRegistrationId() {
        return result.hasC2DmRegistrationId();
      }
      public java.lang.String getC2DmRegistrationId() {
        return result.getC2DmRegistrationId();
      }
      public Builder setC2DmRegistrationId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasC2DmRegistrationId = true;
        result.c2DmRegistrationId_ = value;
        return this;
      }
      public Builder clearC2DmRegistrationId() {
        result.hasC2DmRegistrationId = false;
        result.c2DmRegistrationId_ = getDefaultInstance().getC2DmRegistrationId();
        return this;
      }
      
      // optional string client_key = 3;
      public boolean hasClientKey() {
        return result.hasClientKey();
      }
      public java.lang.String getClientKey() {
        return result.getClientKey();
      }
      public Builder setClientKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasClientKey = true;
        result.clientKey_ = value;
        return this;
      }
      public Builder clearClientKey() {
        result.hasClientKey = false;
        result.clientKey_ = getDefaultInstance().getClientKey();
        return this;
      }
      
      // optional string sender_id = 4;
      public boolean hasSenderId() {
        return result.hasSenderId();
      }
      public java.lang.String getSenderId() {
        return result.getSenderId();
      }
      public Builder setSenderId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSenderId = true;
        result.senderId_ = value;
        return this;
      }
      public Builder clearSenderId() {
        result.hasSenderId = false;
        result.senderId_ = getDefaultInstance().getSenderId();
        return this;
      }
      
      // optional .com.google.protos.ipc.invalidation.Version channel_version = 5;
      public boolean hasChannelVersion() {
        return result.hasChannelVersion();
      }
      public com.google.protos.ipc.invalidation.ClientProtocol.Version getChannelVersion() {
        return result.getChannelVersion();
      }
      public Builder setChannelVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChannelVersion = true;
        result.channelVersion_ = value;
        return this;
      }
      public Builder setChannelVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder builderForValue) {
        result.hasChannelVersion = true;
        result.channelVersion_ = builderForValue.build();
        return this;
      }
      public Builder mergeChannelVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (result.hasChannelVersion() &&
            result.channelVersion_ != com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance()) {
          result.channelVersion_ =
            com.google.protos.ipc.invalidation.ClientProtocol.Version.newBuilder(result.channelVersion_).mergeFrom(value).buildPartial();
        } else {
          result.channelVersion_ = value;
        }
        result.hasChannelVersion = true;
        return this;
      }
      public Builder clearChannelVersion() {
        result.hasChannelVersion = false;
        result.channelVersion_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
        return this;
      }
      
      // optional string package_name = 6;
      public boolean hasPackageName() {
        return result.hasPackageName();
      }
      public java.lang.String getPackageName() {
        return result.getPackageName();
      }
      public Builder setPackageName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPackageName = true;
        result.packageName_ = value;
        return this;
      }
      public Builder clearPackageName() {
        result.hasPackageName = false;
        result.packageName_ = getDefaultInstance().getPackageName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.EndpointId)
    }
    
    static {
      defaultInstance = new EndpointId(true);
      com.google.protos.ipc.invalidation.AndroidChannel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.EndpointId)
  }
  
  public static final class AddressedAndroidMessage extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AddressedAndroidMessage.newBuilder() to construct.
    private AddressedAndroidMessage() {
      initFields();
    }
    private AddressedAndroidMessage(boolean noInit) {}
    
    private static final AddressedAndroidMessage defaultInstance;
    public static AddressedAndroidMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressedAndroidMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional string client_key = 1;
    public static final int CLIENT_KEY_FIELD_NUMBER = 1;
    private boolean hasClientKey;
    private java.lang.String clientKey_ = "";
    public boolean hasClientKey() { return hasClientKey; }
    public java.lang.String getClientKey() { return clientKey_; }
    
    // optional bytes message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private boolean hasMessage;
    private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessage() { return hasMessage; }
    public com.google.protobuf.ByteString getMessage() { return message_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasClientKey()) {
        output.writeString(1, getClientKey());
      }
      if (hasMessage()) {
        output.writeBytes(2, getMessage());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasClientKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getClientKey());
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessage());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage, Builder> {
      private com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage result;
      
      // Construct using com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage other) {
        if (other == com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.getDefaultInstance()) return this;
        if (other.hasClientKey()) {
          setClientKey(other.getClientKey());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              setClientKey(input.readString());
              break;
            }
            case 18: {
              setMessage(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional string client_key = 1;
      public boolean hasClientKey() {
        return result.hasClientKey();
      }
      public java.lang.String getClientKey() {
        return result.getClientKey();
      }
      public Builder setClientKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasClientKey = true;
        result.clientKey_ = value;
        return this;
      }
      public Builder clearClientKey() {
        result.hasClientKey = false;
        result.clientKey_ = getDefaultInstance().getClientKey();
        return this;
      }
      
      // optional bytes message = 2;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public com.google.protobuf.ByteString getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessage)
    }
    
    static {
      defaultInstance = new AddressedAndroidMessage(true);
      com.google.protos.ipc.invalidation.AndroidChannel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessage)
  }
  
  public static final class AddressedAndroidMessageBatch extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AddressedAndroidMessageBatch.newBuilder() to construct.
    private AddressedAndroidMessageBatch() {
      initFields();
    }
    private AddressedAndroidMessageBatch(boolean noInit) {}
    
    private static final AddressedAndroidMessageBatch defaultInstance;
    public static AddressedAndroidMessageBatch getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressedAndroidMessageBatch getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;
    public static final int ADDRESSED_MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> addressedMessage_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> getAddressedMessageList() {
      return addressedMessage_;
    }
    public int getAddressedMessageCount() { return addressedMessage_.size(); }
    public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage getAddressedMessage(int index) {
      return addressedMessage_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage element : getAddressedMessageList()) {
        output.writeMessage(1, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage element : getAddressedMessageList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch, Builder> {
      private com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch result;
      
      // Construct using com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.addressedMessage_ != java.util.Collections.EMPTY_LIST) {
          result.addressedMessage_ =
            java.util.Collections.unmodifiableList(result.addressedMessage_);
        }
        com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch other) {
        if (other == com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessageBatch.getDefaultInstance()) return this;
        if (!other.addressedMessage_.isEmpty()) {
          if (result.addressedMessage_.isEmpty()) {
            result.addressedMessage_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage>();
          }
          result.addressedMessage_.addAll(other.addressedMessage_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.Builder subBuilder = com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAddressedMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.google.protos.ipc.invalidation.AddressedAndroidMessage addressed_message = 1;
      public java.util.List<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> getAddressedMessageList() {
        return java.util.Collections.unmodifiableList(result.addressedMessage_);
      }
      public int getAddressedMessageCount() {
        return result.getAddressedMessageCount();
      }
      public com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage getAddressedMessage(int index) {
        return result.getAddressedMessage(index);
      }
      public Builder setAddressedMessage(int index, com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.addressedMessage_.set(index, value);
        return this;
      }
      public Builder setAddressedMessage(int index, com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.Builder builderForValue) {
        result.addressedMessage_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAddressedMessage(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.addressedMessage_.isEmpty()) {
          result.addressedMessage_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage>();
        }
        result.addressedMessage_.add(value);
        return this;
      }
      public Builder addAddressedMessage(com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage.Builder builderForValue) {
        if (result.addressedMessage_.isEmpty()) {
          result.addressedMessage_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage>();
        }
        result.addressedMessage_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAddressedMessage(
          java.lang.Iterable<? extends com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage> values) {
        if (result.addressedMessage_.isEmpty()) {
          result.addressedMessage_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidChannel.AddressedAndroidMessage>();
        }
        super.addAll(values, result.addressedMessage_);
        return this;
      }
      public Builder clearAddressedMessage() {
        result.addressedMessage_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessageBatch)
    }
    
    static {
      defaultInstance = new AddressedAndroidMessageBatch(true);
      com.google.protos.ipc.invalidation.AndroidChannel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedAndroidMessageBatch)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
