// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/android_state.proto

package com.google.protos.ipc.invalidation;

public final class AndroidState {
  private AndroidState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class ClientMetadata extends
      com.google.protobuf.GeneratedMessageLite {
    // Use ClientMetadata.newBuilder() to construct.
    private ClientMetadata() {
      initFields();
    }
    private ClientMetadata(boolean noInit) {}
    
    private static final ClientMetadata defaultInstance;
    public static ClientMetadata getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .com.google.protos.ipc.invalidation.Version version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private boolean hasVersion;
    private com.google.protos.ipc.invalidation.ClientProtocol.Version version_;
    public boolean hasVersion() { return hasVersion; }
    public com.google.protos.ipc.invalidation.ClientProtocol.Version getVersion() { return version_; }
    
    // optional string client_key = 2;
    public static final int CLIENT_KEY_FIELD_NUMBER = 2;
    private boolean hasClientKey;
    private java.lang.String clientKey_ = "";
    public boolean hasClientKey() { return hasClientKey; }
    public java.lang.String getClientKey() { return clientKey_; }
    
    // optional int32 client_type = 3;
    public static final int CLIENT_TYPE_FIELD_NUMBER = 3;
    private boolean hasClientType;
    private int clientType_ = 0;
    public boolean hasClientType() { return hasClientType; }
    public int getClientType() { return clientType_; }
    
    // optional string account_name = 4;
    public static final int ACCOUNT_NAME_FIELD_NUMBER = 4;
    private boolean hasAccountName;
    private java.lang.String accountName_ = "";
    public boolean hasAccountName() { return hasAccountName; }
    public java.lang.String getAccountName() { return accountName_; }
    
    // optional string account_type = 5;
    public static final int ACCOUNT_TYPE_FIELD_NUMBER = 5;
    private boolean hasAccountType;
    private java.lang.String accountType_ = "";
    public boolean hasAccountType() { return hasAccountType; }
    public java.lang.String getAccountType() { return accountType_; }
    
    // optional string auth_type = 6;
    public static final int AUTH_TYPE_FIELD_NUMBER = 6;
    private boolean hasAuthType;
    private java.lang.String authType_ = "";
    public boolean hasAuthType() { return hasAuthType; }
    public java.lang.String getAuthType() { return authType_; }
    
    // optional string listener_pkg = 7;
    public static final int LISTENER_PKG_FIELD_NUMBER = 7;
    private boolean hasListenerPkg;
    private java.lang.String listenerPkg_ = "";
    public boolean hasListenerPkg() { return hasListenerPkg; }
    public java.lang.String getListenerPkg() { return listenerPkg_; }
    
    // optional string listener_class = 8;
    public static final int LISTENER_CLASS_FIELD_NUMBER = 8;
    private boolean hasListenerClass;
    private java.lang.String listenerClass_ = "";
    public boolean hasListenerClass() { return hasListenerClass; }
    public java.lang.String getListenerClass() { return listenerClass_; }
    
    private void initFields() {
      version_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVersion()) {
        output.writeMessage(1, getVersion());
      }
      if (hasClientKey()) {
        output.writeString(2, getClientKey());
      }
      if (hasClientType()) {
        output.writeInt32(3, getClientType());
      }
      if (hasAccountName()) {
        output.writeString(4, getAccountName());
      }
      if (hasAccountType()) {
        output.writeString(5, getAccountType());
      }
      if (hasAuthType()) {
        output.writeString(6, getAuthType());
      }
      if (hasListenerPkg()) {
        output.writeString(7, getListenerPkg());
      }
      if (hasListenerClass()) {
        output.writeString(8, getListenerClass());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getVersion());
      }
      if (hasClientKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getClientKey());
      }
      if (hasClientType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getClientType());
      }
      if (hasAccountName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getAccountName());
      }
      if (hasAccountType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getAccountType());
      }
      if (hasAuthType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getAuthType());
      }
      if (hasListenerPkg()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getListenerPkg());
      }
      if (hasListenerClass()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getListenerClass());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidState.ClientMetadata, Builder> {
      private com.google.protos.ipc.invalidation.AndroidState.ClientMetadata result;
      
      // Construct using com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.AndroidState.ClientMetadata();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.AndroidState.ClientMetadata internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.AndroidState.ClientMetadata();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.AndroidState.ClientMetadata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.AndroidState.ClientMetadata returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata other) {
        if (other == com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          mergeVersion(other.getVersion());
        }
        if (other.hasClientKey()) {
          setClientKey(other.getClientKey());
        }
        if (other.hasClientType()) {
          setClientType(other.getClientType());
        }
        if (other.hasAccountName()) {
          setAccountName(other.getAccountName());
        }
        if (other.hasAccountType()) {
          setAccountType(other.getAccountType());
        }
        if (other.hasAuthType()) {
          setAuthType(other.getAuthType());
        }
        if (other.hasListenerPkg()) {
          setListenerPkg(other.getListenerPkg());
        }
        if (other.hasListenerClass()) {
          setListenerClass(other.getListenerClass());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder subBuilder = com.google.protos.ipc.invalidation.ClientProtocol.Version.newBuilder();
              if (hasVersion()) {
                subBuilder.mergeFrom(getVersion());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVersion(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setClientKey(input.readString());
              break;
            }
            case 24: {
              setClientType(input.readInt32());
              break;
            }
            case 34: {
              setAccountName(input.readString());
              break;
            }
            case 42: {
              setAccountType(input.readString());
              break;
            }
            case 50: {
              setAuthType(input.readString());
              break;
            }
            case 58: {
              setListenerPkg(input.readString());
              break;
            }
            case 66: {
              setListenerClass(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.Version version = 1;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public com.google.protos.ipc.invalidation.ClientProtocol.Version getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder setVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version.Builder builderForValue) {
        result.hasVersion = true;
        result.version_ = builderForValue.build();
        return this;
      }
      public Builder mergeVersion(com.google.protos.ipc.invalidation.ClientProtocol.Version value) {
        if (result.hasVersion() &&
            result.version_ != com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance()) {
          result.version_ =
            com.google.protos.ipc.invalidation.ClientProtocol.Version.newBuilder(result.version_).mergeFrom(value).buildPartial();
        } else {
          result.version_ = value;
        }
        result.hasVersion = true;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = com.google.protos.ipc.invalidation.ClientProtocol.Version.getDefaultInstance();
        return this;
      }
      
      // optional string client_key = 2;
      public boolean hasClientKey() {
        return result.hasClientKey();
      }
      public java.lang.String getClientKey() {
        return result.getClientKey();
      }
      public Builder setClientKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasClientKey = true;
        result.clientKey_ = value;
        return this;
      }
      public Builder clearClientKey() {
        result.hasClientKey = false;
        result.clientKey_ = getDefaultInstance().getClientKey();
        return this;
      }
      
      // optional int32 client_type = 3;
      public boolean hasClientType() {
        return result.hasClientType();
      }
      public int getClientType() {
        return result.getClientType();
      }
      public Builder setClientType(int value) {
        result.hasClientType = true;
        result.clientType_ = value;
        return this;
      }
      public Builder clearClientType() {
        result.hasClientType = false;
        result.clientType_ = 0;
        return this;
      }
      
      // optional string account_name = 4;
      public boolean hasAccountName() {
        return result.hasAccountName();
      }
      public java.lang.String getAccountName() {
        return result.getAccountName();
      }
      public Builder setAccountName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccountName = true;
        result.accountName_ = value;
        return this;
      }
      public Builder clearAccountName() {
        result.hasAccountName = false;
        result.accountName_ = getDefaultInstance().getAccountName();
        return this;
      }
      
      // optional string account_type = 5;
      public boolean hasAccountType() {
        return result.hasAccountType();
      }
      public java.lang.String getAccountType() {
        return result.getAccountType();
      }
      public Builder setAccountType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccountType = true;
        result.accountType_ = value;
        return this;
      }
      public Builder clearAccountType() {
        result.hasAccountType = false;
        result.accountType_ = getDefaultInstance().getAccountType();
        return this;
      }
      
      // optional string auth_type = 6;
      public boolean hasAuthType() {
        return result.hasAuthType();
      }
      public java.lang.String getAuthType() {
        return result.getAuthType();
      }
      public Builder setAuthType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAuthType = true;
        result.authType_ = value;
        return this;
      }
      public Builder clearAuthType() {
        result.hasAuthType = false;
        result.authType_ = getDefaultInstance().getAuthType();
        return this;
      }
      
      // optional string listener_pkg = 7;
      public boolean hasListenerPkg() {
        return result.hasListenerPkg();
      }
      public java.lang.String getListenerPkg() {
        return result.getListenerPkg();
      }
      public Builder setListenerPkg(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasListenerPkg = true;
        result.listenerPkg_ = value;
        return this;
      }
      public Builder clearListenerPkg() {
        result.hasListenerPkg = false;
        result.listenerPkg_ = getDefaultInstance().getListenerPkg();
        return this;
      }
      
      // optional string listener_class = 8;
      public boolean hasListenerClass() {
        return result.hasListenerClass();
      }
      public java.lang.String getListenerClass() {
        return result.getListenerClass();
      }
      public Builder setListenerClass(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasListenerClass = true;
        result.listenerClass_ = value;
        return this;
      }
      public Builder clearListenerClass() {
        result.hasListenerClass = false;
        result.listenerClass_ = getDefaultInstance().getListenerClass();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ClientMetadata)
    }
    
    static {
      defaultInstance = new ClientMetadata(true);
      com.google.protos.ipc.invalidation.AndroidState.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ClientMetadata)
  }
  
  public static final class ClientProperty extends
      com.google.protobuf.GeneratedMessageLite {
    // Use ClientProperty.newBuilder() to construct.
    private ClientProperty() {
      initFields();
    }
    private ClientProperty(boolean noInit) {}
    
    private static final ClientProperty defaultInstance;
    public static ClientProperty getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientProperty getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // optional bytes value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasValue() { return hasValue; }
    public com.google.protobuf.ByteString getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasValue()) {
        output.writeBytes(2, getValue());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValue());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.ClientProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidState.ClientProperty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidState.ClientProperty, Builder> {
      private com.google.protos.ipc.invalidation.AndroidState.ClientProperty result;
      
      // Construct using com.google.protos.ipc.invalidation.AndroidState.ClientProperty.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.AndroidState.ClientProperty();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.AndroidState.ClientProperty internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.AndroidState.ClientProperty();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidState.ClientProperty.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.AndroidState.ClientProperty buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.AndroidState.ClientProperty returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidState.ClientProperty other) {
        if (other == com.google.protos.ipc.invalidation.AndroidState.ClientProperty.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setValue(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // optional bytes value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public com.google.protobuf.ByteString getValue() {
        return result.getValue();
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ClientProperty)
    }
    
    static {
      defaultInstance = new ClientProperty(true);
      com.google.protos.ipc.invalidation.AndroidState.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ClientProperty)
  }
  
  public static final class StoredState extends
      com.google.protobuf.GeneratedMessageLite {
    // Use StoredState.newBuilder() to construct.
    private StoredState() {
      initFields();
    }
    private StoredState(boolean noInit) {}
    
    private static final StoredState defaultInstance;
    public static StoredState getDefaultInstance() {
      return defaultInstance;
    }
    
    public StoredState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;
    public static final int METADATA_FIELD_NUMBER = 1;
    private boolean hasMetadata;
    private com.google.protos.ipc.invalidation.AndroidState.ClientMetadata metadata_;
    public boolean hasMetadata() { return hasMetadata; }
    public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata getMetadata() { return metadata_; }
    
    // repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;
    public static final int PROPERTY_FIELD_NUMBER = 9;
    private java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> property_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> getPropertyList() {
      return property_;
    }
    public int getPropertyCount() { return property_.size(); }
    public com.google.protos.ipc.invalidation.AndroidState.ClientProperty getProperty(int index) {
      return property_.get(index);
    }
    
    private void initFields() {
      metadata_ = com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMetadata()) {
        output.writeMessage(1, getMetadata());
      }
      for (com.google.protos.ipc.invalidation.AndroidState.ClientProperty element : getPropertyList()) {
        output.writeMessage(9, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMetadata()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMetadata());
      }
      for (com.google.protos.ipc.invalidation.AndroidState.ClientProperty element : getPropertyList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, element);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.AndroidState.StoredState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.AndroidState.StoredState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.AndroidState.StoredState, Builder> {
      private com.google.protos.ipc.invalidation.AndroidState.StoredState result;
      
      // Construct using com.google.protos.ipc.invalidation.AndroidState.StoredState.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.AndroidState.StoredState();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.AndroidState.StoredState internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.AndroidState.StoredState();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.AndroidState.StoredState getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.AndroidState.StoredState.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.AndroidState.StoredState build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.AndroidState.StoredState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.AndroidState.StoredState buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.property_ != java.util.Collections.EMPTY_LIST) {
          result.property_ =
            java.util.Collections.unmodifiableList(result.property_);
        }
        com.google.protos.ipc.invalidation.AndroidState.StoredState returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.AndroidState.StoredState other) {
        if (other == com.google.protos.ipc.invalidation.AndroidState.StoredState.getDefaultInstance()) return this;
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        if (!other.property_.isEmpty()) {
          if (result.property_.isEmpty()) {
            result.property_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidState.ClientProperty>();
          }
          result.property_.addAll(other.property_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.Builder subBuilder = com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.newBuilder();
              if (hasMetadata()) {
                subBuilder.mergeFrom(getMetadata());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMetadata(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.google.protos.ipc.invalidation.AndroidState.ClientProperty.Builder subBuilder = com.google.protos.ipc.invalidation.AndroidState.ClientProperty.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperty(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.ClientMetadata metadata = 1;
      public boolean hasMetadata() {
        return result.hasMetadata();
      }
      public com.google.protos.ipc.invalidation.AndroidState.ClientMetadata getMetadata() {
        return result.getMetadata();
      }
      public Builder setMetadata(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMetadata = true;
        result.metadata_ = value;
        return this;
      }
      public Builder setMetadata(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.Builder builderForValue) {
        result.hasMetadata = true;
        result.metadata_ = builderForValue.build();
        return this;
      }
      public Builder mergeMetadata(com.google.protos.ipc.invalidation.AndroidState.ClientMetadata value) {
        if (result.hasMetadata() &&
            result.metadata_ != com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance()) {
          result.metadata_ =
            com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.newBuilder(result.metadata_).mergeFrom(value).buildPartial();
        } else {
          result.metadata_ = value;
        }
        result.hasMetadata = true;
        return this;
      }
      public Builder clearMetadata() {
        result.hasMetadata = false;
        result.metadata_ = com.google.protos.ipc.invalidation.AndroidState.ClientMetadata.getDefaultInstance();
        return this;
      }
      
      // repeated .com.google.protos.ipc.invalidation.ClientProperty property = 9;
      public java.util.List<com.google.protos.ipc.invalidation.AndroidState.ClientProperty> getPropertyList() {
        return java.util.Collections.unmodifiableList(result.property_);
      }
      public int getPropertyCount() {
        return result.getPropertyCount();
      }
      public com.google.protos.ipc.invalidation.AndroidState.ClientProperty getProperty(int index) {
        return result.getProperty(index);
      }
      public Builder setProperty(int index, com.google.protos.ipc.invalidation.AndroidState.ClientProperty value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.property_.set(index, value);
        return this;
      }
      public Builder setProperty(int index, com.google.protos.ipc.invalidation.AndroidState.ClientProperty.Builder builderForValue) {
        result.property_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProperty(com.google.protos.ipc.invalidation.AndroidState.ClientProperty value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.property_.isEmpty()) {
          result.property_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidState.ClientProperty>();
        }
        result.property_.add(value);
        return this;
      }
      public Builder addProperty(com.google.protos.ipc.invalidation.AndroidState.ClientProperty.Builder builderForValue) {
        if (result.property_.isEmpty()) {
          result.property_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidState.ClientProperty>();
        }
        result.property_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProperty(
          java.lang.Iterable<? extends com.google.protos.ipc.invalidation.AndroidState.ClientProperty> values) {
        if (result.property_.isEmpty()) {
          result.property_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.AndroidState.ClientProperty>();
        }
        super.addAll(values, result.property_);
        return this;
      }
      public Builder clearProperty() {
        result.property_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.StoredState)
    }
    
    static {
      defaultInstance = new StoredState(true);
      com.google.protos.ipc.invalidation.AndroidState.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.StoredState)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
