// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/channel.proto

package com.google.protos.ipc.invalidation;

public final class Channel {
  private Channel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class NetworkEndpointId extends
      com.google.protobuf.GeneratedMessageLite {
    // Use NetworkEndpointId.newBuilder() to construct.
    private NetworkEndpointId() {
      initFields();
    }
    private NetworkEndpointId(boolean noInit) {}
    
    private static final NetworkEndpointId defaultInstance;
    public static NetworkEndpointId getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetworkEndpointId getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum NetworkAddress
        implements com.google.protobuf.Internal.EnumLite {
      TEST(0, 1),
      ANDROID(1, 113),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static NetworkAddress valueOf(int value) {
        switch (value) {
          case 1: return TEST;
          case 113: return ANDROID;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<NetworkAddress>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NetworkAddress>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetworkAddress>() {
              public NetworkAddress findValueByNumber(int number) {
                return NetworkAddress.valueOf(number)
      ;        }
            };
      
      private final int index;
      private final int value;
      private NetworkAddress(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress)
    }
    
    // optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;
    public static final int NETWORK_ADDRESS_FIELD_NUMBER = 1;
    private boolean hasNetworkAddress;
    private com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress networkAddress_;
    public boolean hasNetworkAddress() { return hasNetworkAddress; }
    public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress getNetworkAddress() { return networkAddress_; }
    
    // optional bytes client_address = 2;
    public static final int CLIENT_ADDRESS_FIELD_NUMBER = 2;
    private boolean hasClientAddress;
    private com.google.protobuf.ByteString clientAddress_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasClientAddress() { return hasClientAddress; }
    public com.google.protobuf.ByteString getClientAddress() { return clientAddress_; }
    
    private void initFields() {
      networkAddress_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.TEST;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasNetworkAddress()) {
        output.writeEnum(1, getNetworkAddress().getNumber());
      }
      if (hasClientAddress()) {
        output.writeBytes(2, getClientAddress());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasNetworkAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getNetworkAddress().getNumber());
      }
      if (hasClientAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientAddress());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.NetworkEndpointId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Channel.NetworkEndpointId, Builder> {
      private com.google.protos.ipc.invalidation.Channel.NetworkEndpointId result;
      
      // Construct using com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Channel.NetworkEndpointId();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Channel.NetworkEndpointId internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Channel.NetworkEndpointId();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Channel.NetworkEndpointId buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Channel.NetworkEndpointId returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId other) {
        if (other == com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.getDefaultInstance()) return this;
        if (other.hasNetworkAddress()) {
          setNetworkAddress(other.getNetworkAddress());
        }
        if (other.hasClientAddress()) {
          setClientAddress(other.getClientAddress());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress value = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.valueOf(rawValue);
              if (value != null) {
                setNetworkAddress(value);
              }
              break;
            }
            case 18: {
              setClientAddress(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.NetworkEndpointId.NetworkAddress network_address = 1;
      public boolean hasNetworkAddress() {
        return result.hasNetworkAddress();
      }
      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress getNetworkAddress() {
        return result.getNetworkAddress();
      }
      public Builder setNetworkAddress(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNetworkAddress = true;
        result.networkAddress_ = value;
        return this;
      }
      public Builder clearNetworkAddress() {
        result.hasNetworkAddress = false;
        result.networkAddress_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.NetworkAddress.TEST;
        return this;
      }
      
      // optional bytes client_address = 2;
      public boolean hasClientAddress() {
        return result.hasClientAddress();
      }
      public com.google.protobuf.ByteString getClientAddress() {
        return result.getClientAddress();
      }
      public Builder setClientAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasClientAddress = true;
        result.clientAddress_ = value;
        return this;
      }
      public Builder clearClientAddress() {
        result.hasClientAddress = false;
        result.clientAddress_ = getDefaultInstance().getClientAddress();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.NetworkEndpointId)
    }
    
    static {
      defaultInstance = new NetworkEndpointId(true);
      com.google.protos.ipc.invalidation.Channel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.NetworkEndpointId)
  }
  
  public static final class AddressedMessage extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AddressedMessage.newBuilder() to construct.
    private AddressedMessage() {
      initFields();
    }
    private AddressedMessage(boolean noInit) {}
    
    private static final AddressedMessage defaultInstance;
    public static AddressedMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressedMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .com.google.protos.ipc.invalidation.ChannelMessageEncoding.MessageEncoding encoding = 1;
    public static final int ENCODING_FIELD_NUMBER = 1;
    private boolean hasEncoding;
    private com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding encoding_;
    public boolean hasEncoding() { return hasEncoding; }
    public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding getEncoding() { return encoding_; }
    
    // optional bytes auth_user_id = 2;
    public static final int AUTH_USER_ID_FIELD_NUMBER = 2;
    private boolean hasAuthUserId;
    private com.google.protobuf.ByteString authUserId_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasAuthUserId() { return hasAuthUserId; }
    public com.google.protobuf.ByteString getAuthUserId() { return authUserId_; }
    
    // optional .com.google.protos.ipc.invalidation.NetworkEndpointId client_network_id = 3;
    public static final int CLIENT_NETWORK_ID_FIELD_NUMBER = 3;
    private boolean hasClientNetworkId;
    private com.google.protos.ipc.invalidation.Channel.NetworkEndpointId clientNetworkId_;
    public boolean hasClientNetworkId() { return hasClientNetworkId; }
    public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId getClientNetworkId() { return clientNetworkId_; }
    
    // optional bytes network_message = 4;
    public static final int NETWORK_MESSAGE_FIELD_NUMBER = 4;
    private boolean hasNetworkMessage;
    private com.google.protobuf.ByteString networkMessage_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasNetworkMessage() { return hasNetworkMessage; }
    public com.google.protobuf.ByteString getNetworkMessage() { return networkMessage_; }
    
    // optional string caller_info = 5;
    public static final int CALLER_INFO_FIELD_NUMBER = 5;
    private boolean hasCallerInfo;
    private java.lang.String callerInfo_ = "";
    public boolean hasCallerInfo() { return hasCallerInfo; }
    public java.lang.String getCallerInfo() { return callerInfo_; }
    
    private void initFields() {
      encoding_ = com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding.PROTOBUF_BINARY_FORMAT;
      clientNetworkId_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasEncoding()) {
        output.writeEnum(1, getEncoding().getNumber());
      }
      if (hasAuthUserId()) {
        output.writeBytes(2, getAuthUserId());
      }
      if (hasClientNetworkId()) {
        output.writeMessage(3, getClientNetworkId());
      }
      if (hasNetworkMessage()) {
        output.writeBytes(4, getNetworkMessage());
      }
      if (hasCallerInfo()) {
        output.writeString(5, getCallerInfo());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasEncoding()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getEncoding().getNumber());
      }
      if (hasAuthUserId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAuthUserId());
      }
      if (hasClientNetworkId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getClientNetworkId());
      }
      if (hasNetworkMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNetworkMessage());
      }
      if (hasCallerInfo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getCallerInfo());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Channel.AddressedMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Channel.AddressedMessage, Builder> {
      private com.google.protos.ipc.invalidation.Channel.AddressedMessage result;
      
      // Construct using com.google.protos.ipc.invalidation.Channel.AddressedMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Channel.AddressedMessage();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Channel.AddressedMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Channel.AddressedMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessage getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Channel.AddressedMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Channel.AddressedMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Channel.AddressedMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Channel.AddressedMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Channel.AddressedMessage other) {
        if (other == com.google.protos.ipc.invalidation.Channel.AddressedMessage.getDefaultInstance()) return this;
        if (other.hasEncoding()) {
          setEncoding(other.getEncoding());
        }
        if (other.hasAuthUserId()) {
          setAuthUserId(other.getAuthUserId());
        }
        if (other.hasClientNetworkId()) {
          mergeClientNetworkId(other.getClientNetworkId());
        }
        if (other.hasNetworkMessage()) {
          setNetworkMessage(other.getNetworkMessage());
        }
        if (other.hasCallerInfo()) {
          setCallerInfo(other.getCallerInfo());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding value = com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding.valueOf(rawValue);
              if (value != null) {
                setEncoding(value);
              }
              break;
            }
            case 18: {
              setAuthUserId(input.readBytes());
              break;
            }
            case 26: {
              com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.Builder subBuilder = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.newBuilder();
              if (hasClientNetworkId()) {
                subBuilder.mergeFrom(getClientNetworkId());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClientNetworkId(subBuilder.buildPartial());
              break;
            }
            case 34: {
              setNetworkMessage(input.readBytes());
              break;
            }
            case 42: {
              setCallerInfo(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.ChannelMessageEncoding.MessageEncoding encoding = 1;
      public boolean hasEncoding() {
        return result.hasEncoding();
      }
      public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding getEncoding() {
        return result.getEncoding();
      }
      public Builder setEncoding(com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEncoding = true;
        result.encoding_ = value;
        return this;
      }
      public Builder clearEncoding() {
        result.hasEncoding = false;
        result.encoding_ = com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.MessageEncoding.PROTOBUF_BINARY_FORMAT;
        return this;
      }
      
      // optional bytes auth_user_id = 2;
      public boolean hasAuthUserId() {
        return result.hasAuthUserId();
      }
      public com.google.protobuf.ByteString getAuthUserId() {
        return result.getAuthUserId();
      }
      public Builder setAuthUserId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAuthUserId = true;
        result.authUserId_ = value;
        return this;
      }
      public Builder clearAuthUserId() {
        result.hasAuthUserId = false;
        result.authUserId_ = getDefaultInstance().getAuthUserId();
        return this;
      }
      
      // optional .com.google.protos.ipc.invalidation.NetworkEndpointId client_network_id = 3;
      public boolean hasClientNetworkId() {
        return result.hasClientNetworkId();
      }
      public com.google.protos.ipc.invalidation.Channel.NetworkEndpointId getClientNetworkId() {
        return result.getClientNetworkId();
      }
      public Builder setClientNetworkId(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasClientNetworkId = true;
        result.clientNetworkId_ = value;
        return this;
      }
      public Builder setClientNetworkId(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.Builder builderForValue) {
        result.hasClientNetworkId = true;
        result.clientNetworkId_ = builderForValue.build();
        return this;
      }
      public Builder mergeClientNetworkId(com.google.protos.ipc.invalidation.Channel.NetworkEndpointId value) {
        if (result.hasClientNetworkId() &&
            result.clientNetworkId_ != com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.getDefaultInstance()) {
          result.clientNetworkId_ =
            com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.newBuilder(result.clientNetworkId_).mergeFrom(value).buildPartial();
        } else {
          result.clientNetworkId_ = value;
        }
        result.hasClientNetworkId = true;
        return this;
      }
      public Builder clearClientNetworkId() {
        result.hasClientNetworkId = false;
        result.clientNetworkId_ = com.google.protos.ipc.invalidation.Channel.NetworkEndpointId.getDefaultInstance();
        return this;
      }
      
      // optional bytes network_message = 4;
      public boolean hasNetworkMessage() {
        return result.hasNetworkMessage();
      }
      public com.google.protobuf.ByteString getNetworkMessage() {
        return result.getNetworkMessage();
      }
      public Builder setNetworkMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNetworkMessage = true;
        result.networkMessage_ = value;
        return this;
      }
      public Builder clearNetworkMessage() {
        result.hasNetworkMessage = false;
        result.networkMessage_ = getDefaultInstance().getNetworkMessage();
        return this;
      }
      
      // optional string caller_info = 5;
      public boolean hasCallerInfo() {
        return result.hasCallerInfo();
      }
      public java.lang.String getCallerInfo() {
        return result.getCallerInfo();
      }
      public Builder setCallerInfo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCallerInfo = true;
        result.callerInfo_ = value;
        return this;
      }
      public Builder clearCallerInfo() {
        result.hasCallerInfo = false;
        result.callerInfo_ = getDefaultInstance().getCallerInfo();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedMessage)
    }
    
    static {
      defaultInstance = new AddressedMessage(true);
      com.google.protos.ipc.invalidation.Channel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedMessage)
  }
  
  public static final class AddressedMessageResponse extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AddressedMessageResponse.newBuilder() to construct.
    private AddressedMessageResponse() {
      initFields();
    }
    private AddressedMessageResponse(boolean noInit) {}
    
    private static final AddressedMessageResponse defaultInstance;
    public static AddressedMessageResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressedMessageResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse, Builder> {
      private com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse result;
      
      // Construct using com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse other) {
        if (other == com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse.getDefaultInstance()) return this;
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedMessageResponse)
    }
    
    static {
      defaultInstance = new AddressedMessageResponse(true);
      com.google.protos.ipc.invalidation.Channel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedMessageResponse)
  }
  
  public static final class AddressedMessageBatch extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AddressedMessageBatch.newBuilder() to construct.
    private AddressedMessageBatch() {
      initFields();
    }
    private AddressedMessageBatch(boolean noInit) {}
    
    private static final AddressedMessageBatch defaultInstance;
    public static AddressedMessageBatch getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressedMessageBatch getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .com.google.protos.ipc.invalidation.AddressedMessage requests = 1;
    public static final int REQUESTS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protos.ipc.invalidation.Channel.AddressedMessage> requests_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protos.ipc.invalidation.Channel.AddressedMessage> getRequestsList() {
      return requests_;
    }
    public int getRequestsCount() { return requests_.size(); }
    public com.google.protos.ipc.invalidation.Channel.AddressedMessage getRequests(int index) {
      return requests_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.google.protos.ipc.invalidation.Channel.AddressedMessage element : getRequestsList()) {
        output.writeMessage(1, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.google.protos.ipc.invalidation.Channel.AddressedMessage element : getRequestsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch, Builder> {
      private com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch result;
      
      // Construct using com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.requests_ != java.util.Collections.EMPTY_LIST) {
          result.requests_ =
            java.util.Collections.unmodifiableList(result.requests_);
        }
        com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch other) {
        if (other == com.google.protos.ipc.invalidation.Channel.AddressedMessageBatch.getDefaultInstance()) return this;
        if (!other.requests_.isEmpty()) {
          if (result.requests_.isEmpty()) {
            result.requests_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessage>();
          }
          result.requests_.addAll(other.requests_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.Channel.AddressedMessage.Builder subBuilder = com.google.protos.ipc.invalidation.Channel.AddressedMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRequests(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.google.protos.ipc.invalidation.AddressedMessage requests = 1;
      public java.util.List<com.google.protos.ipc.invalidation.Channel.AddressedMessage> getRequestsList() {
        return java.util.Collections.unmodifiableList(result.requests_);
      }
      public int getRequestsCount() {
        return result.getRequestsCount();
      }
      public com.google.protos.ipc.invalidation.Channel.AddressedMessage getRequests(int index) {
        return result.getRequests(index);
      }
      public Builder setRequests(int index, com.google.protos.ipc.invalidation.Channel.AddressedMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.requests_.set(index, value);
        return this;
      }
      public Builder setRequests(int index, com.google.protos.ipc.invalidation.Channel.AddressedMessage.Builder builderForValue) {
        result.requests_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRequests(com.google.protos.ipc.invalidation.Channel.AddressedMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.requests_.isEmpty()) {
          result.requests_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessage>();
        }
        result.requests_.add(value);
        return this;
      }
      public Builder addRequests(com.google.protos.ipc.invalidation.Channel.AddressedMessage.Builder builderForValue) {
        if (result.requests_.isEmpty()) {
          result.requests_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessage>();
        }
        result.requests_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRequests(
          java.lang.Iterable<? extends com.google.protos.ipc.invalidation.Channel.AddressedMessage> values) {
        if (result.requests_.isEmpty()) {
          result.requests_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessage>();
        }
        super.addAll(values, result.requests_);
        return this;
      }
      public Builder clearRequests() {
        result.requests_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedMessageBatch)
    }
    
    static {
      defaultInstance = new AddressedMessageBatch(true);
      com.google.protos.ipc.invalidation.Channel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedMessageBatch)
  }
  
  public static final class AddressedMessageBatchResponse extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AddressedMessageBatchResponse.newBuilder() to construct.
    private AddressedMessageBatchResponse() {
      initFields();
    }
    private AddressedMessageBatchResponse(boolean noInit) {}
    
    private static final AddressedMessageBatchResponse defaultInstance;
    public static AddressedMessageBatchResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressedMessageBatchResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .com.google.protos.ipc.invalidation.AddressedMessageResponse responses = 1;
    public static final int RESPONSES_FIELD_NUMBER = 1;
    private java.util.List<com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse> responses_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse> getResponsesList() {
      return responses_;
    }
    public int getResponsesCount() { return responses_.size(); }
    public com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse getResponses(int index) {
      return responses_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse element : getResponsesList()) {
        output.writeMessage(1, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse element : getResponsesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse, Builder> {
      private com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse result;
      
      // Construct using com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.responses_ != java.util.Collections.EMPTY_LIST) {
          result.responses_ =
            java.util.Collections.unmodifiableList(result.responses_);
        }
        com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse other) {
        if (other == com.google.protos.ipc.invalidation.Channel.AddressedMessageBatchResponse.getDefaultInstance()) return this;
        if (!other.responses_.isEmpty()) {
          if (result.responses_.isEmpty()) {
            result.responses_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse>();
          }
          result.responses_.addAll(other.responses_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse.Builder subBuilder = com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResponses(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.google.protos.ipc.invalidation.AddressedMessageResponse responses = 1;
      public java.util.List<com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse> getResponsesList() {
        return java.util.Collections.unmodifiableList(result.responses_);
      }
      public int getResponsesCount() {
        return result.getResponsesCount();
      }
      public com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse getResponses(int index) {
        return result.getResponses(index);
      }
      public Builder setResponses(int index, com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.responses_.set(index, value);
        return this;
      }
      public Builder setResponses(int index, com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse.Builder builderForValue) {
        result.responses_.set(index, builderForValue.build());
        return this;
      }
      public Builder addResponses(com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.responses_.isEmpty()) {
          result.responses_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse>();
        }
        result.responses_.add(value);
        return this;
      }
      public Builder addResponses(com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse.Builder builderForValue) {
        if (result.responses_.isEmpty()) {
          result.responses_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse>();
        }
        result.responses_.add(builderForValue.build());
        return this;
      }
      public Builder addAllResponses(
          java.lang.Iterable<? extends com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse> values) {
        if (result.responses_.isEmpty()) {
          result.responses_ = new java.util.ArrayList<com.google.protos.ipc.invalidation.Channel.AddressedMessageResponse>();
        }
        super.addAll(values, result.responses_);
        return this;
      }
      public Builder clearResponses() {
        result.responses_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AddressedMessageBatchResponse)
    }
    
    static {
      defaultInstance = new AddressedMessageBatchResponse(true);
      com.google.protos.ipc.invalidation.Channel.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AddressedMessageBatchResponse)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
