// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/channel_common.proto

package com.google.protos.ipc.invalidation;

public final class ChannelCommon {
  private ChannelCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class ChannelMessageEncoding extends
      com.google.protobuf.GeneratedMessageLite {
    // Use ChannelMessageEncoding.newBuilder() to construct.
    private ChannelMessageEncoding() {
      initFields();
    }
    private ChannelMessageEncoding(boolean noInit) {}
    
    private static final ChannelMessageEncoding defaultInstance;
    public static ChannelMessageEncoding getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChannelMessageEncoding getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum MessageEncoding
        implements com.google.protobuf.Internal.EnumLite {
      PROTOBUF_BINARY_FORMAT(0, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static MessageEncoding valueOf(int value) {
        switch (value) {
          case 1: return PROTOBUF_BINARY_FORMAT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageEncoding>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageEncoding>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEncoding>() {
              public MessageEncoding findValueByNumber(int number) {
                return MessageEncoding.valueOf(number)
      ;        }
            };
      
      private final int index;
      private final int value;
      private MessageEncoding(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.ChannelMessageEncoding.MessageEncoding)
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding, Builder> {
      private com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding result;
      
      // Construct using com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding other) {
        if (other == com.google.protos.ipc.invalidation.ChannelCommon.ChannelMessageEncoding.getDefaultInstance()) return this;
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ChannelMessageEncoding)
    }
    
    static {
      defaultInstance = new ChannelMessageEncoding(true);
      com.google.protos.ipc.invalidation.ChannelCommon.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ChannelMessageEncoding)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
