// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/client.proto

package com.google.protos.ipc.invalidation;

public final class Client {
  private Client() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class AckHandleP extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AckHandleP.newBuilder() to construct.
    private AckHandleP() {
      initFields();
    }
    private AckHandleP(boolean noInit) {}
    
    private static final AckHandleP defaultInstance;
    public static AckHandleP getDefaultInstance() {
      return defaultInstance;
    }
    
    public AckHandleP getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;
    public static final int INVALIDATION_FIELD_NUMBER = 1;
    private boolean hasInvalidation;
    private com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP invalidation_;
    public boolean hasInvalidation() { return hasInvalidation; }
    public com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP getInvalidation() { return invalidation_; }
    
    private void initFields() {
      invalidation_ = com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasInvalidation()) {
        output.writeMessage(1, getInvalidation());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasInvalidation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInvalidation());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.AckHandleP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.AckHandleP prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.AckHandleP, Builder> {
      private com.google.protos.ipc.invalidation.Client.AckHandleP result;
      
      // Construct using com.google.protos.ipc.invalidation.Client.AckHandleP.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Client.AckHandleP();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Client.AckHandleP internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Client.AckHandleP();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Client.AckHandleP getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.AckHandleP.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Client.AckHandleP build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Client.AckHandleP buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Client.AckHandleP buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Client.AckHandleP returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.AckHandleP other) {
        if (other == com.google.protos.ipc.invalidation.Client.AckHandleP.getDefaultInstance()) return this;
        if (other.hasInvalidation()) {
          mergeInvalidation(other.getInvalidation());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.Builder subBuilder = com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.newBuilder();
              if (hasInvalidation()) {
                subBuilder.mergeFrom(getInvalidation());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInvalidation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.InvalidationP invalidation = 1;
      public boolean hasInvalidation() {
        return result.hasInvalidation();
      }
      public com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP getInvalidation() {
        return result.getInvalidation();
      }
      public Builder setInvalidation(com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasInvalidation = true;
        result.invalidation_ = value;
        return this;
      }
      public Builder setInvalidation(com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.Builder builderForValue) {
        result.hasInvalidation = true;
        result.invalidation_ = builderForValue.build();
        return this;
      }
      public Builder mergeInvalidation(com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP value) {
        if (result.hasInvalidation() &&
            result.invalidation_ != com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance()) {
          result.invalidation_ =
            com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.newBuilder(result.invalidation_).mergeFrom(value).buildPartial();
        } else {
          result.invalidation_ = value;
        }
        result.hasInvalidation = true;
        return this;
      }
      public Builder clearInvalidation() {
        result.hasInvalidation = false;
        result.invalidation_ = com.google.protos.ipc.invalidation.ClientProtocol.InvalidationP.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.AckHandleP)
    }
    
    static {
      defaultInstance = new AckHandleP(true);
      com.google.protos.ipc.invalidation.Client.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.AckHandleP)
  }
  
  public static final class PersistentTiclState extends
      com.google.protobuf.GeneratedMessageLite {
    // Use PersistentTiclState.newBuilder() to construct.
    private PersistentTiclState() {
      initFields();
    }
    private PersistentTiclState(boolean noInit) {}
    
    private static final PersistentTiclState defaultInstance;
    public static PersistentTiclState getDefaultInstance() {
      return defaultInstance;
    }
    
    public PersistentTiclState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional bytes client_token = 1;
    public static final int CLIENT_TOKEN_FIELD_NUMBER = 1;
    private boolean hasClientToken;
    private com.google.protobuf.ByteString clientToken_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasClientToken() { return hasClientToken; }
    public com.google.protobuf.ByteString getClientToken() { return clientToken_; }
    
    // optional int64 last_message_send_time_ms = 2 [default = 0];
    public static final int LAST_MESSAGE_SEND_TIME_MS_FIELD_NUMBER = 2;
    private boolean hasLastMessageSendTimeMs;
    private long lastMessageSendTimeMs_ = 0L;
    public boolean hasLastMessageSendTimeMs() { return hasLastMessageSendTimeMs; }
    public long getLastMessageSendTimeMs() { return lastMessageSendTimeMs_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasClientToken()) {
        output.writeBytes(1, getClientToken());
      }
      if (hasLastMessageSendTimeMs()) {
        output.writeInt64(2, getLastMessageSendTimeMs());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasClientToken()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClientToken());
      }
      if (hasLastMessageSendTimeMs()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getLastMessageSendTimeMs());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentTiclState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.PersistentTiclState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.PersistentTiclState, Builder> {
      private com.google.protos.ipc.invalidation.Client.PersistentTiclState result;
      
      // Construct using com.google.protos.ipc.invalidation.Client.PersistentTiclState.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Client.PersistentTiclState();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Client.PersistentTiclState internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Client.PersistentTiclState();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Client.PersistentTiclState getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Client.PersistentTiclState build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Client.PersistentTiclState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Client.PersistentTiclState buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Client.PersistentTiclState returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.PersistentTiclState other) {
        if (other == com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance()) return this;
        if (other.hasClientToken()) {
          setClientToken(other.getClientToken());
        }
        if (other.hasLastMessageSendTimeMs()) {
          setLastMessageSendTimeMs(other.getLastMessageSendTimeMs());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              setClientToken(input.readBytes());
              break;
            }
            case 16: {
              setLastMessageSendTimeMs(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // optional bytes client_token = 1;
      public boolean hasClientToken() {
        return result.hasClientToken();
      }
      public com.google.protobuf.ByteString getClientToken() {
        return result.getClientToken();
      }
      public Builder setClientToken(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasClientToken = true;
        result.clientToken_ = value;
        return this;
      }
      public Builder clearClientToken() {
        result.hasClientToken = false;
        result.clientToken_ = getDefaultInstance().getClientToken();
        return this;
      }
      
      // optional int64 last_message_send_time_ms = 2 [default = 0];
      public boolean hasLastMessageSendTimeMs() {
        return result.hasLastMessageSendTimeMs();
      }
      public long getLastMessageSendTimeMs() {
        return result.getLastMessageSendTimeMs();
      }
      public Builder setLastMessageSendTimeMs(long value) {
        result.hasLastMessageSendTimeMs = true;
        result.lastMessageSendTimeMs_ = value;
        return this;
      }
      public Builder clearLastMessageSendTimeMs() {
        result.hasLastMessageSendTimeMs = false;
        result.lastMessageSendTimeMs_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.PersistentTiclState)
    }
    
    static {
      defaultInstance = new PersistentTiclState(true);
      com.google.protos.ipc.invalidation.Client.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.PersistentTiclState)
  }
  
  public static final class PersistentStateBlob extends
      com.google.protobuf.GeneratedMessageLite {
    // Use PersistentStateBlob.newBuilder() to construct.
    private PersistentStateBlob() {
      initFields();
    }
    private PersistentStateBlob(boolean noInit) {}
    
    private static final PersistentStateBlob defaultInstance;
    public static PersistentStateBlob getDefaultInstance() {
      return defaultInstance;
    }
    
    public PersistentStateBlob getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;
    public static final int TICL_STATE_FIELD_NUMBER = 1;
    private boolean hasTiclState;
    private com.google.protos.ipc.invalidation.Client.PersistentTiclState ticlState_;
    public boolean hasTiclState() { return hasTiclState; }
    public com.google.protos.ipc.invalidation.Client.PersistentTiclState getTiclState() { return ticlState_; }
    
    // optional bytes authentication_code = 2;
    public static final int AUTHENTICATION_CODE_FIELD_NUMBER = 2;
    private boolean hasAuthenticationCode;
    private com.google.protobuf.ByteString authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasAuthenticationCode() { return hasAuthenticationCode; }
    public com.google.protobuf.ByteString getAuthenticationCode() { return authenticationCode_; }
    
    private void initFields() {
      ticlState_ = com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTiclState()) {
        output.writeMessage(1, getTiclState());
      }
      if (hasAuthenticationCode()) {
        output.writeBytes(2, getAuthenticationCode());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTiclState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTiclState());
      }
      if (hasAuthenticationCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAuthenticationCode());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Client.PersistentStateBlob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Client.PersistentStateBlob prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Client.PersistentStateBlob, Builder> {
      private com.google.protos.ipc.invalidation.Client.PersistentStateBlob result;
      
      // Construct using com.google.protos.ipc.invalidation.Client.PersistentStateBlob.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Client.PersistentStateBlob();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Client.PersistentStateBlob internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Client.PersistentStateBlob();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Client.PersistentStateBlob getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Client.PersistentStateBlob.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Client.PersistentStateBlob build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Client.PersistentStateBlob buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Client.PersistentStateBlob buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Client.PersistentStateBlob returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Client.PersistentStateBlob other) {
        if (other == com.google.protos.ipc.invalidation.Client.PersistentStateBlob.getDefaultInstance()) return this;
        if (other.hasTiclState()) {
          mergeTiclState(other.getTiclState());
        }
        if (other.hasAuthenticationCode()) {
          setAuthenticationCode(other.getAuthenticationCode());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              com.google.protos.ipc.invalidation.Client.PersistentTiclState.Builder subBuilder = com.google.protos.ipc.invalidation.Client.PersistentTiclState.newBuilder();
              if (hasTiclState()) {
                subBuilder.mergeFrom(getTiclState());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTiclState(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setAuthenticationCode(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.PersistentTiclState ticl_state = 1;
      public boolean hasTiclState() {
        return result.hasTiclState();
      }
      public com.google.protos.ipc.invalidation.Client.PersistentTiclState getTiclState() {
        return result.getTiclState();
      }
      public Builder setTiclState(com.google.protos.ipc.invalidation.Client.PersistentTiclState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasTiclState = true;
        result.ticlState_ = value;
        return this;
      }
      public Builder setTiclState(com.google.protos.ipc.invalidation.Client.PersistentTiclState.Builder builderForValue) {
        result.hasTiclState = true;
        result.ticlState_ = builderForValue.build();
        return this;
      }
      public Builder mergeTiclState(com.google.protos.ipc.invalidation.Client.PersistentTiclState value) {
        if (result.hasTiclState() &&
            result.ticlState_ != com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance()) {
          result.ticlState_ =
            com.google.protos.ipc.invalidation.Client.PersistentTiclState.newBuilder(result.ticlState_).mergeFrom(value).buildPartial();
        } else {
          result.ticlState_ = value;
        }
        result.hasTiclState = true;
        return this;
      }
      public Builder clearTiclState() {
        result.hasTiclState = false;
        result.ticlState_ = com.google.protos.ipc.invalidation.Client.PersistentTiclState.getDefaultInstance();
        return this;
      }
      
      // optional bytes authentication_code = 2;
      public boolean hasAuthenticationCode() {
        return result.hasAuthenticationCode();
      }
      public com.google.protobuf.ByteString getAuthenticationCode() {
        return result.getAuthenticationCode();
      }
      public Builder setAuthenticationCode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAuthenticationCode = true;
        result.authenticationCode_ = value;
        return this;
      }
      public Builder clearAuthenticationCode() {
        result.hasAuthenticationCode = false;
        result.authenticationCode_ = getDefaultInstance().getAuthenticationCode();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.PersistentStateBlob)
    }
    
    static {
      defaultInstance = new PersistentStateBlob(true);
      com.google.protos.ipc.invalidation.Client.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.PersistentStateBlob)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
