// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types.proto

package com.google.protos.ipc.invalidation;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class ClientType extends
      com.google.protobuf.GeneratedMessageLite {
    // Use ClientType.newBuilder() to construct.
    private ClientType() {
      initFields();
    }
    private ClientType(boolean noInit) {}
    
    private static final ClientType defaultInstance;
    public static ClientType getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientType getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      INTERNAL(0, 1),
      TEST(1, 2),
      CHROME_SYNC(2, 1004),
      CHROME_SYNC_ANDROID(3, 1018),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return INTERNAL;
          case 2: return TEST;
          case 1004: return CHROME_SYNC;
          case 1018: return CHROME_SYNC_ANDROID;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number)
      ;        }
            };
      
      private final int index;
      private final int value;
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.ClientType.Type)
    }
    
    // optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.google.protos.ipc.invalidation.Types.ClientType.Type type_;
    public boolean hasType() { return hasType; }
    public com.google.protos.ipc.invalidation.Types.ClientType.Type getType() { return type_; }
    
    private void initFields() {
      type_ = com.google.protos.ipc.invalidation.Types.ClientType.Type.INTERNAL;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ClientType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Types.ClientType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Types.ClientType, Builder> {
      private com.google.protos.ipc.invalidation.Types.ClientType result;
      
      // Construct using com.google.protos.ipc.invalidation.Types.ClientType.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Types.ClientType();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Types.ClientType internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Types.ClientType();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Types.ClientType getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Types.ClientType.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Types.ClientType build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Types.ClientType buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Types.ClientType buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Types.ClientType returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Types.ClientType other) {
        if (other == com.google.protos.ipc.invalidation.Types.ClientType.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.Types.ClientType.Type value = com.google.protos.ipc.invalidation.Types.ClientType.Type.valueOf(rawValue);
              if (value != null) {
                setType(value);
              }
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.ClientType.Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public com.google.protos.ipc.invalidation.Types.ClientType.Type getType() {
        return result.getType();
      }
      public Builder setType(com.google.protos.ipc.invalidation.Types.ClientType.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.google.protos.ipc.invalidation.Types.ClientType.Type.INTERNAL;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ClientType)
    }
    
    static {
      defaultInstance = new ClientType(true);
      com.google.protos.ipc.invalidation.Types.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ClientType)
  }
  
  public static final class ObjectSource extends
      com.google.protobuf.GeneratedMessageLite {
    // Use ObjectSource.newBuilder() to construct.
    private ObjectSource() {
      initFields();
    }
    private ObjectSource(boolean noInit) {}
    
    private static final ObjectSource defaultInstance;
    public static ObjectSource getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObjectSource getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      INTERNAL(0, 1),
      TEST(1, 2),
      CHROME_SYNC(2, 1004),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return INTERNAL;
          case 2: return TEST;
          case 1004: return CHROME_SYNC;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number)
      ;        }
            };
      
      private final int index;
      private final int value;
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.ObjectSource.Type)
    }
    
    // optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private com.google.protos.ipc.invalidation.Types.ObjectSource.Type type_;
    public boolean hasType() { return hasType; }
    public com.google.protos.ipc.invalidation.Types.ObjectSource.Type getType() { return type_; }
    
    private void initFields() {
      type_ = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.INTERNAL;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.ObjectSource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Types.ObjectSource prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Types.ObjectSource, Builder> {
      private com.google.protos.ipc.invalidation.Types.ObjectSource result;
      
      // Construct using com.google.protos.ipc.invalidation.Types.ObjectSource.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Types.ObjectSource();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Types.ObjectSource internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Types.ObjectSource();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Types.ObjectSource getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Types.ObjectSource.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Types.ObjectSource build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Types.ObjectSource buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Types.ObjectSource buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Types.ObjectSource returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Types.ObjectSource other) {
        if (other == com.google.protos.ipc.invalidation.Types.ObjectSource.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.protos.ipc.invalidation.Types.ObjectSource.Type value = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.valueOf(rawValue);
              if (value != null) {
                setType(value);
              }
              break;
            }
          }
        }
      }
      
      
      // optional .com.google.protos.ipc.invalidation.ObjectSource.Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public com.google.protos.ipc.invalidation.Types.ObjectSource.Type getType() {
        return result.getType();
      }
      public Builder setType(com.google.protos.ipc.invalidation.Types.ObjectSource.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.google.protos.ipc.invalidation.Types.ObjectSource.Type.INTERNAL;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.ObjectSource)
    }
    
    static {
      defaultInstance = new ObjectSource(true);
      com.google.protos.ipc.invalidation.Types.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.ObjectSource)
  }
  
  public static final class Constants extends
      com.google.protobuf.GeneratedMessageLite {
    // Use Constants.newBuilder() to construct.
    private Constants() {
      initFields();
    }
    private Constants(boolean noInit) {}
    
    private static final Constants defaultInstance;
    public static Constants getDefaultInstance() {
      return defaultInstance;
    }
    
    public Constants getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum ObjectVersion
        implements com.google.protobuf.Internal.EnumLite {
      UNKNOWN(0, 0),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static ObjectVersion valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ObjectVersion>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ObjectVersion>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ObjectVersion>() {
              public ObjectVersion findValueByNumber(int number) {
                return ObjectVersion.valueOf(number)
      ;        }
            };
      
      private final int index;
      private final int value;
      private ObjectVersion(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.google.protos.ipc.invalidation.Constants.ObjectVersion)
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.protos.ipc.invalidation.Types.Constants parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protos.ipc.invalidation.Types.Constants prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.protos.ipc.invalidation.Types.Constants, Builder> {
      private com.google.protos.ipc.invalidation.Types.Constants result;
      
      // Construct using com.google.protos.ipc.invalidation.Types.Constants.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.protos.ipc.invalidation.Types.Constants();
        return builder;
      }
      
      protected com.google.protos.ipc.invalidation.Types.Constants internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.protos.ipc.invalidation.Types.Constants();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protos.ipc.invalidation.Types.Constants getDefaultInstanceForType() {
        return com.google.protos.ipc.invalidation.Types.Constants.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.protos.ipc.invalidation.Types.Constants build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.protos.ipc.invalidation.Types.Constants buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.protos.ipc.invalidation.Types.Constants buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.protos.ipc.invalidation.Types.Constants returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protos.ipc.invalidation.Types.Constants other) {
        if (other == com.google.protos.ipc.invalidation.Types.Constants.getDefaultInstance()) return this;
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.google.protos.ipc.invalidation.Constants)
    }
    
    static {
      defaultInstance = new Constants(true);
      com.google.protos.ipc.invalidation.Types.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.protos.ipc.invalidation.Constants)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
